### ISSUE TITLE
Failure on .Net Core 2.1

### ISSUE THREAD

**Issue by rmihalache** [antiufo/roslyn-linq-rewrite#23]
Hello,

I am trying to use Roslyn-linq-rewrite with a .NET Core 2.1 console app.
Because it is a sln/csproj I understand I need to use the command line. However, regardless of whether I specify the sln or the csproj file, I get this error:

H:\Test projects\LinqOptimiser>"H:\Test projects\LinqOptimiser\roslyn-linq-rewrite.exe" "H:\Test projects\LinqOptimiser\LinqOptimiser\LinqOptimiser.csproj"
Installing dependencies for first use.
  Restore completed in 62.08 ms for H:\Test projects\LinqOptimiser\LinqOptimiser\LinqOptimiser.csproj.
Microsoft (R) Build Engine version 15.8.169+g1ccb72aefa for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 55.96 ms for H:\Test projects\LinqOptimiser\LinqOptimiser\LinqOptimiser.csproj.
  LinqOptimiser -> H:\Test projects\LinqOptimiser\LinqOptimiser\bin\Debug\netcoreapp2.1\LinqOptimiser.dll
  LinqOptimiser -> H:\Test projects\LinqOptimiser\LinqOptimiser\bin\Debug\netcoreapp2.1\publish\
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\<user name>\.nuget/packages\microsoft.diasymreader.native/1.5.0-beta1/runtimes/win/native/Microsoft.DiaSymReader.Native.amd64.dll'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at Program.CopyTo(String source, String destinationFolder)
   at Program.MainInternal(String[] args)
   at Program.Main(String[] args)
System.Exception: An error occured.
   at Shaman.Roslyn.LinqRewrite.Program.EnsureInstalled()
   at Shaman.Roslyn.LinqRewrite.Program.MainInternal(String[] args)
   at Shaman.Roslyn.LinqRewrite.Program.Main(String[] args)

I have downloaded the latest version from github.

Thanks!

**Comment by bmeverett** [comment]
I'm getting the same error on .net core 2.1

**Comment by bmeverett** [comment]
I copied `microsoft.diasymreader.native/1.5.0-beta1` to my .nuget folder to see if that would help. I'm still getting an error with `Microsoft.CodeAnalysis.Workspaces.Desktop`

```
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.CodeAnalysis.Workspaces.Desktop, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.CodeAnalysis.Workspaces.Desktop, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Shaman.Roslyn.LinqRewrite.Program.CompileSolution(String path, IReadOnlyList`1 projectNames, Boolean release, Boolean generateResources, Boolean useInternalBuildProcess, Boolean detailed)
   at Shaman.Roslyn.LinqRewrite.Program.MainInternal(String[] args)
   at Shaman.Roslyn.LinqRewrite.Program.Main(String[] args)
```
